name: Build artifacts

on: [ push ]

env:
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
      
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Pull & update submodules recursively
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote

      - name: Build image
        run: |
          docker build -t ameba_rtl8720dn .

      - name: Build firmware
        run: |
          docker run --rm \
            -v $GITHUB_WORKSPACE:/workdir \
            ameba_rtl8720dn \
            /bin/bash -c 'chmod -R 777 /workdir/ambd_sdk/project && \
            cd /workdir/ambd_sdk/project/realtek_amebaD_va0_example/GCC-RELEASE/project_lp && make all && \
            cd /workdir/ambd_sdk/project/realtek_amebaD_va0_example/GCC-RELEASE/project_hp && make all'

      - name: Upload firmware files
        uses: actions/upload-artifact@v3
        with:
          name: FW-binaries
          path: |
            /home/runner/work/RTL8720DN_AT/RTL8720DN_AT/ambd_sdk/project/realtek_amebaD_va0_example/GCC-RELEASE/project_hp/asdk/image/km4_image2_all.bin
            /home/runner/work/RTL8720DN_AT/RTL8720DN_AT/ambd_sdk/project/realtek_amebaD_va0_example/GCC-RELEASE/project_hp/asdk/image/km4_boot_all.bin
            /home/runner/work/RTL8720DN_AT/RTL8720DN_AT/ambd_sdk/project/realtek_amebaD_va0_example/GCC-RELEASE/project_lp/asdk/image/km0_boot_all.bin
            /home/runner/work/RTL8720DN_AT/RTL8720DN_AT/ambd_sdk/project/realtek_amebaD_va0_example/GCC-RELEASE/project_lp/asdk/image/km0_image2_all.bin
            /home/runner/work/RTL8720DN_AT/RTL8720DN_AT/ambd_sdk/project/realtek_amebaD_va0_example/GCC-RELEASE/project_hp/asdk/image/km0_km4_image2.bin
